@startuml 
skinparam Style strictuml

actor User 
User ->LoginSuccess : Login to page
activate LoginSuccess
deactivate LoginSuccess

ShoppingCart -> ShoppingCart: Add Edit shopping cart
ShoppingCart ->ShoppingCart :save update

LoginSuccess -> ShoppingCart :Manage Shopping cart
activate ShoppingCart
ShoppingCart-> ShoppingCart: list deelte items
deactivate ShoppingCart
 







@enduml