# Generated by Django 3.2 on 2021-04-23 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210423_1550'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='prodcut',
            new_name='product',
        ),
    ]
